version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 606639293354
    BACKEND_REPO: safedeploy-backend
    FRONTEND_REPO: safedeploy

phases:

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      # 🔹 BACKEND BUILD
      - echo Building Backend...
      - docker build -t $BACKEND_REPO -f deployments/docker/backend.Dockerfile .

      # 🔹 FRONTEND BUILD
      - echo Building Frontend...
      - docker build -t $FRONTEND_REPO -f deployments/docker/frontend.Dockerfile .

  post_build:
    commands:
      - echo Tagging Images...

      # 🔹 BACKEND TAG
      - docker tag $BACKEND_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_REPO:latest

      # 🔹 FRONTEND TAG
      - docker tag $FRONTEND_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_REPO:latest

      - echo Pushing Images to ECR...

      # 🔹 PUSH BACKEND
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_REPO:latest

      # 🔹 PUSH FRONTEND
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_REPO:latest

artifacts:
  files:
    - '**/*'
