version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 606639293354

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build backend
      - docker build -t safedeploy-backend ./services/backend-go
      - docker tag safedeploy-backend:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy-backend:latest

      - echo Build frontend
      - docker build -t safedeploy-frontend -f deployments/docker/frontend.Dockerfile .
      - docker tag safedeploy-frontend:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy:latest

  post_build:
    commands:
      - echo Push backend
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy-backend:latest

      - echo Push frontend
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy:latest

      - printf '[{"name":"safedeploy-container-backend","imageUri":"%s"},{"name":"safedeploy-container-frontend","imageUri":"%s"}]' \
        $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy-backend:latest \
        $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/safedeploy:latest \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
