version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ACCOUNT_ID: 606639293354
    BACKEND_REPO: safedeploy-backend
    FRONTEND_REPO: safedeploy

phases:

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Backend...
      - docker build -t $BACKEND_REPO -f deployments/docker/backend.Dockerfile .

      - echo Building Frontend...
      - docker build -t $FRONTEND_REPO -f deployments/docker/frontend.Dockerfile .

  post_build:
    commands:
      - echo Tagging Images...

      - BACKEND_IMAGE=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_REPO:latest
      - FRONTEND_IMAGE=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_REPO:latest

      - docker tag $BACKEND_REPO:latest $BACKEND_IMAGE
      - docker tag $FRONTEND_REPO:latest $FRONTEND_IMAGE

      - echo Pushing Images to ECR...

      - docker push $BACKEND_IMAGE
      - docker push $FRONTEND_IMAGE

      - echo Creating imagedefinitions.json...

      - echo '[{"name":"backend","imageUri":"'"$BACKEND_IMAGE"'"},{"name":"frontend","imageUri":"'"$FRONTEND_IMAGE"'"}]' > imagedefinitions.json

      # 🔍 Debug (optional but helpful)
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
