services:
  backend:
    build:
      context: ../../
      dockerfile: deployments/docker/backend.Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ../../
      dockerfile: deployments/docker/frontend.Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - backend